### ISSUE TITLE
Unknowns show as "nan" in n-gram tab, associated error message

### ISSUE THREAD

**Issue by emhastings** [usnistgov/nestor-tmp2#10]
When I started tagging on the N gram token tab, the ambiguous/unknowns I tagged are showing as nan instead of U, and these tags disappear when you switch between tabs even when saved.  Also, when you click on that entry in the list, an error appears: 
![image](https://user-images.githubusercontent.com/11738850/41792158-ec04cf3c-7625-11e8-9142-a224bdc8de84.png)

The "show details" says "NoneType: None".

The 1 Gram tab seems to work fine (shows U when appropriate). 

For context, I'm tagging the MWO_Maximo_Export data from the auto_data set and using the app.py in the reorg branch to run the app.  I also tried it with the older standalone version of the tool posted in Slack and the same thing happened, although instead of the error message appearing the app just crashes.  This is the traceback message in the console for that version, if that helps: 
![image](https://user-images.githubusercontent.com/11738850/41795498-fbff4c9a-7630-11e8-9c22-b4820c9086fe.png)

**Comment by rtbs-dev** [comment]
Ok, thanks, I'll take a look asap. @saschaMoccozet any idea what would cause the unknown radio button to be `NoneType`ed?

**Comment by saschaMoccozet** [comment]
OK I work on it. I think i have an idea  for "what would cause the unknown radio button to be NoneType" - @tbsexton
But i o not know why "nan" appeared instead of "U" - @emhastings 
I'll work on it ASAP

**Comment by saschaMoccozet** [comment]
The issue has been solved on the DEV branch!

We can close the issue

**Comment by rtbs-dev** [comment]
Awesome! @saschaMoccozet I plan to rebase master onto `reorg` as soon as we get the green light for public (probably release 0.3.0?) Is this bug-fix compatible with reorg?
