### ISSUE TITLE
A test error

### ISSUE THREAD

**Issue by evangelionys** [usnistgov/nestor-tmp2#2]
Hi,
When I used this program to our data, an error occurred.
<img width="756" alt="2017-10-29_180638" src="https://user-images.githubusercontent.com/22282867/32148941-f4cc5038-bcd3-11e7-84e6-279fe772df02.png">
The error:
<img width="771" alt="2017-10-29_181106" src="https://user-images.githubusercontent.com/22282867/32148996-b95f63e0-bcd4-11e7-84db-f31875627cb9.png">
I imported the packages and used the older versions. This is the data I used.
[PSU Maintenance Data.xlsx](https://github.com/usnistgov/ml-py/files/1425536/PSU.Maintenance.Data.xlsx)
Do you have any ideas? Thanks!

**Comment by rtbs-dev** [comment]
Ok so there's an issue in line 130 of `mlp/tools.py` where it's not gracefully checking for pre-existing TEMP files. This will be changed in a future version (hopefully no more extra temp file creation) but in the meantime, try deleting those files and re-running.

**Comment by evangelionys** [comment]
Thanks. There is another error in tool.py probably due to the windows system.
![image](https://user-images.githubusercontent.com/22282867/32239900-3a3098d6-be42-11e7-8d07-fbbabb21fccc.png)
The UnicodeDecodeError raised.
![image](https://user-images.githubusercontent.com/22282867/32240051-9d2e7ade-be42-11e7-8e34-2ab4cd09c730.png)

**Comment by rtbs-dev** [comment]
@evangelionys the most recent push _should_ have dealt with this. I've stopped depending on the codecs package and ported over to builtin's `open(errors='ignore')` in the `line_review()` function in `tools.py`. 

I've now run the toolkit on your data as well, in the Tutorial NB, with no errors. See if you can replicate?
