### ISSUE TITLE
fail when NLPing some header of csv 

### ISSUE THREAD

**Issue by saschaMoccozet** [usnistgov/nestor-tmp2#30]
/nestor/nestor/keyword.py", line 499, in <lambda>
    voc2.loc[mask, 'NE'] = voc2.loc[mask, 'NE'].apply(lambda x: NE_map[x])  # special logic for custom NE type-combinations (config.yaml)
KeyError: 'U UlureU'

The key error changes based on the header opened 
but same file same issue

**Comment by rtbs-dev** [comment]
Solved in 928a1f38751dc3518cfe1e3c5e512a287a494d13, but a more robust regex function for n-gram substitution is 100% necessary in the future.
