### ISSUE TITLE
File Not Found error within release zip

### ISSUE THREAD

**Issue by MichaelPBrundage** [usnistgov/nestor-tmp2#33]
Need to replace logic in `openFilesUI_app.py:150`, since it's splitting on `.` instead of removing the file ext.

**Comment by rtbs-dev** [comment]
Solved with 066f7f1 ; `pathlib.Path()` has a `.stem` and a `.suffix` attribute, which along with `.parent` and `.absolute()` will produce OS-agnostic, name-insensitive filename modifications. Example [here](https://stackoverflow.com/a/45353317)
