### ISSUE TITLE
Readable csv needs a "save to" feature

### ISSUE THREAD

**Issue by MichaelPBrundage** [usnistgov/nestor-tmp2#40]
As of now, when the readable csv button is pushed it saves wherever the user launches the app

**Comment by rtbs-dev** [comment]
more generally, the csv output functionality needs to mimic the h5 output. Haven't had a chance to implement quite yet.

**Comment by rtbs-dev** [comment]
Also, this should not have a 0.2 tag, as 0.2 has already been released. This kind of thing is a good candidate for a revision, along with the documentation edits you were talking about.

**Comment by rtbs-dev** [comment]
@saschaMoccozet this is finished, right? What is the commit for it, again?

**Comment by rtbs-dev** [comment]
Found it, a72f9461ddd0d839cb6632bd5c3faf99e7a1efdf fixes this.
