### ISSUE TITLE
"project oriented UI" issue when setup the special replacement 

### ISSUE THREAD

**Issue by saschaMoccozet** [usnistgov/nestor-tmp2#46]
"    raise ValueError("np.nan is an invalid document, expected byte or "
ValueError: np.nan is an invalid document, expected byte or unicode string."

function extract_1gVocab 
line : list_tokenExtracted = self.tokenExtractor_1Gram.fit_transform(self.clean_rawText)

**Comment by rtbs-dev** [comment]
Update, @saschaMoccozet maybe you can go over the new functionality here, briefly. 

Currently facing an issue with removing "special replace" input, see commit 871ca4d notes. Probably going to move special replace to `edit` menu, not the settings bar.

**Comment by rtbs-dev** [comment]
Fixed with  f20c8c7
