### ISSUE TITLE
Opening Preferences closes Nestor

### ISSUE THREAD

**Issue by msngit** [usnistgov/nestor-tmp2#48]
System details : Mac OS High Sierra.

To replicate, create a new project/ open existing project. 
Then click on 'Preferences' - Nestor closes abruptly with the following message on the terminal.

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nestor/ui/taggingUI_app.py", line 712, in setMenu_settings
    iconPath=self.iconPath
  File "/anaconda3/lib/python3.6/site-packages/nestor/ui/meta_windows.py", line 149, in __init__
    for key, value in specialReplace.items():
AttributeError: 'str' object has no attribute 'items'
Abort trap: 6

**Comment by rtbs-dev** [comment]
Interesting, @saschaMoccozet  can you check this out? Looks like the special replace is being set as a str in some cases, instead of a dict? 

@msngit are you running the latest dev? I'm prepping a pull to the master branch, but in the meantime try the dev branch.

**Comment by msngit** [comment]
This error has since been taken care by changes regarding specialReplace, as seen in the latest dev version.
Thus closing it.
