### ISSUE TITLE
Unknowns not being parsed by keyword extractor

### ISSUE THREAD

**Issue by rtbs-dev** [usnistgov/nestor-tmp2#5]
E.g., here's the three untagged work orders (tag-empty): 

|      | RawText                      | Items   | Problem   | Solution   | eXcess   | Redundant   | UK_tok             |
|-----:|:-----------------------------|:--------|:----------|:-----------|:---------|:------------|:-------------------|
|  631 | unload automation not return |         |           |            |          |             | unload, automation |
| 2562 | camshaft standstill gary     |         |           |            |          |             | camshaft           |
| 3185 | disti water empty water fill |         |           |            |          |             | disti, fill        |

`return` is definitely in the vocab list, as "U" (found via the `<KeywordExtractor>.vocab()` attr.) So, why isn't it showing up? 

@saschaMoccozet  maybe the `.transform()` method is broken again?

**Comment by saschaMoccozet** [comment]
did it found it before we change the code ? (when there is 2 time the checking )

**Comment by rtbs-dev** [comment]
it turns out it was that `.trasform` func, which wasn't even keeping thinks marked as "U", only things that were NOT it in the vocab list to start with....I think we need two separate labels for those two types of unknowns.?

**Comment by rtbs-dev** [comment]
Solved with [this commit](https://github.com/usnistgov/ml-py/commit/a476280522eceecf45a4a31924901dc794a86ea2)
