### ISSUE TITLE
nestor-dash 0.3 incompatibility

### ISSUE THREAD

**Issue by rtbs-dev** [usnistgov/nestor-tmp2#53]
after the project-oriented UI update, nestor-dash no longer uses correct imports to check for csv-header mapping

What if new functionality went like this:
1. dash looks in the `.nestor-tmp` folder (created to store projects) for any availabile projects that have an .h5 ready
2. via drop-down, user can select a valid project to analyze
3. dash uses the same directory to read the config file for that project, getting the relevant csv header mapping directly.

**Comment by ghost** [comment]
At the present state, should I not use the dashboard until this is fixed or re-factored?

**Comment by rtbs-dev** [comment]
should be fixed via ae74b45; stay tuned for v0.3 full release for an update to pip.
