### ISSUE TITLE
Failure to Update Tag Extraction

### ISSUE THREAD

**Issue by ghost** [usnistgov/nestor-tmp2#54]
I'm working through the documentation on how to use the tagging tool and following along with the provided excavator files. I reach the point of generating the report and hit the "Update Tag Extraction" button as instructed on pg. 34 of the documentation in Section 2.3.4 Report Tab (Release 0.2.r13). When I click this button the output of the command line shows that the "1 gram tokens" and "N gram tokens" initialize and complete the category loop successfully. 
![cmd_line_status](https://user-images.githubusercontent.com/46032044/50303884-7781ac00-045c-11e9-828a-8716a227f164.PNG)
After the N gram category loop completes, an unhandled error occurs with the description "NoneType:None"
![message](https://user-images.githubusercontent.com/46032044/50303896-7ea8ba00-045c-11e9-8872-975b31a328fd.png)

I tried uninstalling and reinstalling via pip to see if this would help, but the same error occurred.

**Comment by saschaMoccozet** [comment]
@tbsexton could it appeared because 1 or more classification are empty? I remember in the past we got some problem like that ...

**Comment by rtbs-dev** [comment]
Thanks for the report. I think I remember this from an older version...at this stage had you made any annotations, or was it running on a blank vocabulary?

@saschaMoccozet is this something we saw before that was fixed in the dev version?

**Comment by rtbs-dev** [comment]
@saschaMoccozet exactly what I was thinking. I can check if this is still a problem in the current version.

@etbelski Documentation for v0.3 isn't quite live yet, so it's not hosted on PyPi yet, but would you mind trying out the most recent version on the `master` branch? 

`pip install --upgrade git+https://github.com/usnistgov/nestor.git`

If you want to keep the legacy version intact, maybe install this in an environment (e.g. conda, etc.)?

**Comment by ghost** [comment]
@tbsexton I had made a few annotations in the 1 gram and N gram vocab tabs. All words were classified that I had updated. I will try upgrading to latest and see if this changes the behavior.

**Comment by rtbs-dev** [comment]
excellent. Apologies for the lack of documentation on it, though hopefully the improvements are helpful, in general. Feel free to check out the [releases](https://github.com/usnistgov/nestor/releases) tab for some release notes on what to expect.

**Comment by ghost** [comment]
The newest release fixed the problem I was experiencing. Thanks for the guidance and I like the look of v0.3 .

**Comment by sarahlukens** [comment]
I got this same error when I tried creating a csv file in the NESTOR format of tagged words I already had from something else and importing it as the 1-gram file.  It turned out that I had some stuff not formatted in a nestor friendly way, but I spent a little while struggling to figure it out.
