### ISSUE TITLE
ImportError: cannot import name 'load_header_mapping'

### ISSUE THREAD

**Issue by ghost** [usnistgov/nestor-tmp2#57]
Loading in an exported dataset from the nestor-gui, causes the nestor-dash to throw an import error

making directory '.nestor-tmp'
instantiating data connection service
 * Serving Flask app "nestor.dash.views" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
INFO:werkzeug: * Restarting with windowsapi reloader
making directory '.nestor-tmp'
instantiating data connection service
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 324-794-495
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Dec/2018 15:05:49] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Dec/2018 15:05:54] "GET /upload HTTP/1.1" 200 -
data location set to C:\Users\ebelski\.nestor-tmp\excavators_h5.h5
INFO:werkzeug:127.0.0.1 - - [21/Dec/2018 15:06:01] "POST /upload HTTP/1.1" 200 -
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\nestor\dash\plotserve.py", line 12, in <module>
    from nestor.ui import load_header_mapping
ImportError: cannot import name 'load_header_mapping'

**Comment by rtbs-dev** [comment]
Thanks! I'm actually going to close this as a duplicate of #53. The dash has some broken API changes and some poorly supported use-cases of bokeh (see [here](https://github.com/ioam/holoviews/pull/2907) for a PR illustrating this for holoviews from one of our devs)
