### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by emhastings** [usnistgov/nestor-tmp2#58]
Program crashed with following error: 
Traceback (most recent call last):
  File "c:\users\ehast\anaconda3\lib\site-packages\nestor\ui\taggingUI_app.py", line 1961, in onClick_UpdateToSaveVocab
    self.savePercentage_whenUpdate()
  File "c:\users\ehast\anaconda3\lib\site-packages\nestor\ui\taggingUI_app.py", line 1891, in savePercentage_whenUpdate
    if percent1g >= self.savePercentage1gram[0]:
IndexError: list index out of range

This happened with the excavator data first for word 76 (brake), and separately for 92 (access), but not when they are the first word tagged (i.e., when I go back to test the error does not happen again on that word, but somewhere else).
<img width="555" alt="new error" src="https://user-images.githubusercontent.com/11738850/52373252-d22c9280-2a1f-11e9-9470-94222b583b6b.PNG">

**Comment by rtbs-dev** [comment]
I'll have to take a deeper look. @MichaelPBrundage this looks like the same issue that 1aa92a3 solved...thought the issue went away after that?

**Comment by rtbs-dev** [comment]
Should be fixed with  35b11c9 on master. Can you update and report back?

**Comment by emhastings** [comment]
I updated and it looks like it works now-- I'm at least not getting any errors when I try going from brake to access, which was the problem area before.  Thanks!

**Comment by rtbs-dev** [comment]
Great! closing, feel free to comment if it happens again and I'll re-open.
