### ISSUE TITLE
Cannot install Cobrapy 

### ISSUE THREAD

**Issue by Asel35** [usnistgov/nestor-tmp2#66]
Hello, I am new to cobrapy and trying to  install it, but it is giving me this as an error
ERROR: Command errored out with exit status 1: 'c:\users\asem\downloads\python\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\aselm\AppData\Local\Temp\pip-install-bb934msg\python-libsbml-experimental\setup.py'"'"'; file='"'"'C:\Users\aselm\AppData\Local\Temp\pip-install-bb934msg\python-libsbml-experimental\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\aselm\AppData\Local\Temp\pip-record-b5kf2ipt\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\aselm\downloads\python\venv\include\site\python3.8\python-libsbml-experimental' Check the logs for full command output.
******Althought i tried to install it in cmd ( I have a windows 10) , and tried to install it through jupyter in vs code but always same issue. 
Could anyone tell me how to fix this please? thank you !

**Comment by rtbs-dev** [comment]
I think you might be in the wrong repository; this is not related to "cobrapy".
